### PR TITLE
Asintel 1141 ga session data detail

### PR DESCRIPTION
**Pull request by sarmaevanidfe**

### CODE REVIEW

**Review by uhimabindu — COMMENTED** [review]
Q) Why is there another pipeline when we can use existing one?

**Review by uhimabindu — APPROVED** [review]
Approved

**Review by uhimabindu — APPROVED** [review]
Approved

**Review by arvinthseran — APPROVED** [review]

**Review by uhimabindu — APPROVED** [review]
Approved

**Pull request merged**
